fix(power-bi): :bug: Quick filter dropdowns now close when clicking outside popover
equinor/fusion-workspace pull request #605
Opened 2024-04-22 12:43 UTC by EdwardBrunton

### Short summary
Added an overlay to close popover when clicking outside the popover

Link to issue:
https://github.com/equinor/cc-reports/issues/140

### PR Checklist

- [x] I have performed a self-review of my own code
- [x] I have written a short summary of my changes in the PR
- [x] I have linked related issue to the PR
- [x] I have bumped the version(s) in the changed package(s)
- [x] I have bumped the version in workspace-fusion

> [!TIP]
> You can test your changes on the test-application. You can find it under apps\test-app\src\index.tsx

> [!CAUTION]
> ⛔ I understand by merging my PR, the changed packages will be published to NPM immediately ⛔

2024-04-22 13:07 UTC, kjellhaaland requested changes
I think we should consider the overlay not covering the entire window.

Maybe some comment indicating what this "hack" does, for future reference? (Hard to deduct if you dont know the context)

2024-04-22 13:25 UTC, EdwardBrunton commented on packages/power-bi/src/lib/components/quickFilterGroup/QuickFilterGroup.tsx
> +const StyledOverlay = styled.div`
@kjellhaaland why do you want it to not cover the entire screen?

2024-04-22 13:35 UTC, EdwardBrunton commented
> I think we should consider the overlay not covering the entire window.
> 
> Maybe some comment indicating what this "hack" does, for future reference? (Hard to deduct if you dont know the context)

I have left a comment, but I just wanted to say that what you mentioned isn't a hack, it's a common solution in component libraries 😄

2024-04-24 06:54 UTC, Gustav-Eikaas commented
I am more used to seeing something like this, where you attach a ref to the container and subscribe to click events on the whole document. Then you just check if a given click event is inside the ref or not. 

https://github.com/chakra-ui/chakra-ui/blob/dfc81b4d4b3a667055e67fdac39cc17b27742f33/packages/hooks/src/use-outside-click.ts#L25
![image](https://github.com/equinor/fusion-workspace/assets/89254170/ee3bc1ad-7c7b-4eb7-bfc8-3d1669144816)

Are you sure something like this would not work?

2024-04-24 07:14 UTC, EdwardBrunton commented
I'm sure that would work too, but I am not sure why we are trying to overcomplicate this. My proposed solution is very simple, with minimal code, and is a accepted way to do this. See for example [Angular CDK Overlay](https://material.angular.io/cdk/overlay/overview)

2024-04-24 08:10 UTC, Gustav-Eikaas approved these changes

2024-04-24 09:17 UTC, merged